### PR TITLE
Character encoding for example page

### PR DESCRIPTION
**Pull request by ewilligers**
This PR is to test PR preview.

### CODE REVIEW

**Comment by mgiuca** [comment]
Nope, still doesn't seem to work.

See tobie/pr-preview#20 where we thought it was fixed.

**Comment by marcoscaceres** [comment]
Weird... I swear I saw it work in the other PR. Might need to try with an empty commit ?

**Comment by marcoscaceres** [comment]
Oh, this page is not targeted by .pr_preview, only `"src_file": "index.html"` is.

**Comment by mgiuca** [comment]
Oh, d'oh, this one was changing a different index.html. My mistake.

Yeah, pr-preview only affects changes to the spec.

We can close this out, unless you actually want to land the encoding change, @ericwilligers ? In which case, change the description.

**Comment by ewilligers** [comment]
PR Preview is working.

**Pull request closed without merging**
